workspace = { members = [
    "simple-wallet",
    "bip39-simple",
], resolver = "2", dependencies = { serde = { version = "1.0.196", features = [
    "derive",
] }, toml = "0.8.8", blake3 = "1.5.0", bdk = "0.29.0", rand_chacha = "0.3.1", rand_core = { version = "0.6.4", features = [
    "getrandom",
] }, sha2 = "0.10.8" } }
