[package]
name = "base58check"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex-literal.workspace = true
hex.workspace = true
ripemd.workspace = true
sha2.workspace = true
