[package]
name = "simple-wallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bdk.workspace = true
blake3.workspace = true
serde.workspace = true
toml.workspace = true
