[package]
name = "bip39-simple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_chacha.workspace = true
rand_core.workspace = true
sha2.workspace = true
pbkdf2.workspace = true
